creating rabbitmq using ansible

diff --git a/roles/rabbitmq/tasks/main.yml b/roles/rabbitmq/tasks/main.yml
--- a/roles/rabbitmq/tasks/main.yml
+++ b/roles/rabbitmq/tasks/main.yml
@@ -1,3 +1,65 @@
-- name: Print Rabbitmq
-  debug:
-    msg: Rabbitmq
+#source common.sh
+#
+#roboshop_app_password=$1
+#if [ -z "${roboshop_app_password}" ]; then
+#echo -e "\e[31mMissing Roboshop App user password argument\e[0m"
+#exit 1
+#fi
+#
+#print_head "Setup Erlang Repos"
+#curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash  &>>${log_file}
+#status_check $?
+#
+#print_head "Setup RabbitMQ Repos"
+#curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash &>>${log_file}
+#status_check $?
+#
+#print_head "Install Erlang & RabbitMQ"
+#yum install rabbitmq-server erlang -y &>>${log_file}
+#status_check $?
+#
+#print_head "Enable RabbitMQ service"
+#systemctl enable rabbitmq-server &>>${log_file}
+#status_check $?
+#
+#print_head "Start RabbitMQ service"
+#systemctl start rabbitmq-server &>>${log_file}
+#status_check $?
+#
+#print_head "Add Application user"
+#rabbitmqctl list_users | grep roboshop &>>${log_file}
+#if [ $? -ne 0 ]; then
+#rabbitmqctl add_user roboshop ${roboshop_app_password} &>>${log_file}
+#fi
+#status_check $?
+#
+#
+#print_head "Configure Permission for App user"
+#rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*" &>>${log_file}
+#status_check $?
+
+- name: Setup ERLANG Repo
+  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
+- name: Install Rabbitmq Repos
+  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
+- name: Install Erlang and RabbitMQ
+  ansible.builtin.yum:
+    name:
+      - rabbitmq-server
+      - erlang
+    state: installed
+- name: Start RabbitMQ Service
+  ansible.builtin.systemd:
+    name: rabbitmq-server
+    state: started
+    enabled: yes
+
+- name: Add application user
+  community.rabbitmq.rabbitmq_user:
+    user: roboshop
+    password: roboshop123
+    vhost: /
+    configure_priv: .*
+    read_priv: .*
+    write_priv: .*
+    state: present
